# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================

logging:
  level:
    ROOT: DEBUG
    tech.jhipster: DEBUG
    org.hibernate.SQL: DEBUG
    com.orange.qos: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/codeStage
    username: codeStage
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  liquibase:
    contexts: dev, faker
  mail:
    host: localhost
    port: 25
    username:
    password:
  messages:
    cache-duration: PT1S
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  forward-headers-strategy: native

jhipster:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        base64-secret: ODA2OGQ2MjJjYzFhNzc0YzYzYjNhZTU3NDc2ZmQwNDIxZmVjNjkzOTA2YjdlZWIyM2RlMTJiNmE2MzYyMWE3NzViZWViNjIxNTcxZDMwMDVkMDZiM2QyNTljYmI1ZDZmYjlmMmEwMmUzZDI5Zjk0MmVlODIxYjFlZGU3NDg3MzM=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
# Add your custom application properties below
# application:
