package com.orange.qos.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DegradationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDegradationAllPropertiesEquals(Degradation expected, Degradation actual) {
        assertDegradationAutoGeneratedPropertiesEquals(expected, actual);
        assertDegradationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDegradationAllUpdatablePropertiesEquals(Degradation expected, Degradation actual) {
        assertDegradationUpdatableFieldsEquals(expected, actual);
        assertDegradationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDegradationAutoGeneratedPropertiesEquals(Degradation expected, Degradation actual) {
        assertThat(actual)
            .as("Verify Degradation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDegradationUpdatableFieldsEquals(Degradation expected, Degradation actual) {
        assertThat(actual)
            .as("Verify Degradation relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDateSignalement()).as("check dateSignalement").isEqualTo(expected.getDateSignalement()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDegradationUpdatableRelationshipsEquals(Degradation expected, Degradation actual) {
        // empty method
    }
}
